package Main;

import arvore.Arvore;
import gui.Mapa;
import javax.swing.JFrame;
import Main.Singleton;
import arvore.Posicao;
import static gui.Mapa.PREENCHIDO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;


public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaInicial() {
        initComponents();
        jDimensao.setHorizontalAlignment(jDimensao.CENTER);
        //jEntradaX.setHorizontalAlignment(jEntradaX.CENTER);
        //jEntradaY.setHorizontalAlignment(jEntradaY.CENTER);
        //jSaidaX.setHorizontalAlignment(jSaidaX.CENTER);
        //jSaidaY.setHorizontalAlignment(jSaidaY.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField15 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jDimensao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jGeraLabirinto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDimensao.setText("5");
        jDimensao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDimensaoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Tamanho");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("LABIRINTO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Dimensões:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel2.setLayout(null);

        jGeraLabirinto.setText("Gerar Labirinto");
        jGeraLabirinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGeraLabirintoActionPerformed(evt);
            }
        });
        jPanel2.add(jGeraLabirinto);
        jGeraLabirinto.setBounds(135, 5, 235, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jDimensao, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel9)
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jDimensao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGeraLabirintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGeraLabirintoActionPerformed
         geraLabirinto();
        // TODO add your handling code here:
    }//GEN-LAST:event_jGeraLabirintoActionPerformed

    private void jDimensaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDimensaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDimensaoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDimensao;
    private javax.swing.JButton jGeraLabirinto;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField15;
    // End of variables declaration//GEN-END:variables

    public void geraLabirinto(){
        
        int p[] = new int[5];
        try {
        	 p[0] = Integer.parseInt(jDimensao.getText());
		} catch (Exception e) {
			// TODO: handle exception
			p[0] = 5;
		}
        	
        /*
        p[1] = Integer.parseInt(jEntradaX.getText());
        p[2] = Integer.parseInt(jEntradaY.getText());
        p[3] = Integer.parseInt(jSaidaX.getText());
        p[4] = Integer.parseInt(jSaidaY.getText());
        */
        Singleton.getInstance().setTamanhoMatriz(p[0]);
        //Singleton.getInstance().setInicio(new Posicao(p[1], p[2]));
        //Singleton.getInstance().setFim(new Posicao(p[3], p[4]));
        
        //System.out.println("Valores "+Singleton.getInstance().getFim().getX
        
        Singleton.getInstance().setInicio(new Posicao(0, 0));
        Singleton.getInstance().setFim(new Posicao(p[0]-1,p[0]-1));
        
        Arvore a = new Arvore();
        
        JFrame janela = new JFrame("Labirinto");
        janela.setResizable(false);
        janela.setLayout(null);
        janela.setSize(500, 600);
        janela.setLocationRelativeTo(null);
        janela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        janela.setVisible(true);
        
        this.setVisible(false);
             Mapa m = new Mapa(p[0], a);
        janela.add(m);
        
        //rodape
        
        JPanel rodape = new JPanel();
        rodape.setLayout(null);
        //rodape.setOpaque(true);
        rodape.setBounds(0, 500, 494, 50);
        rodape.setBackground(Color.lightGray);
        janela.add(rodape);
        
        //botoes
        JButton finalizar = new JButton("Iniciar Busca");
        finalizar.setBounds(5, 5, 235, 40);
        JButton voltar = new JButton("Voltar");
        voltar.setBounds(250, 5, 235, 40);
        
        finalizar.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {

         
                            m.getC().iniciaArvore(m.getEstado());
                       
                    

                }
		});
            voltar.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
                                   //retornar 
                                   janela.setVisible(false);
                                   new Main().main(null);
				
			}
            
            });
                
        rodape.add(finalizar);
        rodape.add(voltar);
        
        janela.validate();
    }

}

